# Generated by Django 4.2.5 on 2023-09-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('numero_endereco', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
            ],
        ),
    ]
