# Generated by Django 4.2.5 on 2023-09-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0002_bairro_morador_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moradores.bairro'),
        ),
    ]
