# Generated by Django 4.2.5 on 2023-10-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateField()),
                ('bairro', models.CharField(max_length=100)),
                ('quantidade_coletada', models.FloatField()),
                ('unidade_medida', models.CharField(choices=[('toneladas', 'Toneladas'), ('quilo', 'Quilo')], default='toneladas', max_length=10)),
            ],
        ),
    ]
