# Generated by Django 4.2.5 on 2023-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reclamacao', models.CharField(choices=[('nao_recebi', 'Não recebi o saco verde'), ('caminhao_nao_passou', 'Caminhão não passou'), ('saco_rasgado', 'Saco rasgado'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('observacao', models.TextField(max_length=500)),

                ('rua', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(choices=[('area_rural_macatuba', 'Área Rural de Macatuba'), ('centro', 'Centro'), ('distrito_industrial_mario_alves_nunes', 'Distrito Industrial Mario Alves Nunes'), ('jardim_bem_viver', 'Jardim Bem Viver'), ('jardim_capri', 'Jardim Capri'), ('jardim_esperanca', 'Jardim Esperança'), ('jardim_panorama', 'Jardim Panorama'), ('jardim_planalto', 'Jardim Planalto'), ('jardim_santa_ana', 'Jardim Santa Ana'), ('jardim_santa_clara', 'Jardim Santa Clara'), ('jardim_santo_antonio', 'Jardim Santo Antonio'), ('jardim_sonho_meu', 'Jardim Sonho Meu'), ('jardim_veneza', 'Jardim Veneza'), ('nucleo_habitacional_antonio_lorenzetti', 'Núcleo Habitacional Antônio Lorenzetti'), ('nucleo_habitacional_jardim_america', 'Núcleo Habitacional Jardim América'), ('nucleo_habitacional_jardim_bocayuva', 'Núcleo Habitacional Jardim Bocayuva'), ('nucleo_habitacional_jardim_europa', 'Núcleo Habitacional Jardim Europa'), ('nucleo_habitacional_joao_leme_do_prado', 'Núcleo Habitacional João Leme do Prado'), ('nucleo_habitacional_vila_nova', 'Núcleo Habitacional Vila Nova'), ('residencial_azevedo', 'Residencial Azevedo'), ('residencial_riviera', 'Residencial Riviera'), ('vale_verde', 'Vale Verde'), ('vila_do_saber', 'Vila do Saber')], max_length=100)),
                ('numero_casa', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),

            ],
            options={
                'verbose_name': 'Reclamação',
                'verbose_name_plural': 'Reclamações',
                'db_table': 'reclamacoes',
            },
        ),
    ]
