# Generated by Django 4.2.5 on 2023-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reclamacao', models.CharField(choices=[('nao_recebi', 'Não recebi o saco verde'), ('caminhao_nao_passou', 'Caminhão não passou'), ('saco_rasgado', 'Saco rasgado'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('observacao', models.TextField(max_length=500)),
                ('endereco', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Reclamação',
                'verbose_name_plural': 'Reclamações',
                'db_table': 'reclamacoes',
            },
        ),
    ]
