# Generated by Django 4.2.5 on 2023-09-24 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacoes',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='reclamacoes',
            name='historico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamacoes',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('verificado', 'Verificado'), ('resolvido', 'Resolvido'), ('nao_resolvido', 'Não Resolvido')], default='pendente', max_length=20),
        ),
    ]
