# Generated by Django 4.2.5 on 2023-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0002_reclamacoes_data_criacao_reclamacoes_historico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacoes',
            name='historico',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reclamacoes',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('verificado', 'Verificado'), ('resolvido', 'Resolvido'), ('nao_resolvido', 'Não Resolvido')], default='pendente', editable=False, max_length=20),
        ),
    ]
