# Generated by Django 4.2.5 on 2023-09-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0003_alter_reclamacoes_historico_alter_reclamacoes_status'),
        ('reclamacoes', '0004_reclamacoes_nome'),
    ]

    operations = [
    ]
