# Generated by Django 4.2.6 on 2023-10-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0003_alter_reclamacoes_historico_alter_reclamacoes_status'),
        ('reclamacoes', '0004_reclamacoes_nome'),
    ]

    operations = [
    ]
