# Generated by Django 4.2.5 on 2023-10-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0005_merge_20230930_1714'),
        ('reclamacoes', '0005_merge_20231019_1919'),
    ]

    operations = [
    ]
