# Generated by Django 4.2.4 on 2023-10-25 17:55

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0006_reclamacoes_cpf_reclamacoes_cpfopcional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamacoes',
            old_name='cpfOpcional',
            new_name='acompanhareclamacao',
        ),
        migrations.AlterField(
            model_name='reclamacoes',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='reclamacoes',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
