# Generated by Django 4.2.4 on 2023-10-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0007_rename_cpfopcional_reclamacoes_acompanhareclamacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamacoes',
            old_name='acompanhareclamacao',
            new_name='acompanhar_reclamacao',
        ),
        migrations.AlterField(
            model_name='reclamacoes',
            name='historico',
            field=models.TextField(blank=True, default='Aguardando resposta', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reclamacoes',
            name='tipo_reclamacao',
            field=models.CharField(choices=[('nao_recebi', 'NÃO RECEBI O SACO VERDE'), ('caminhao_nao_passou', 'CAMINHÃO NÃO PASSOU'), ('saco_rasgado', 'SACO VERDE RASGADO'), ('saco_insuficiente', 'SACO VERDE INSUFICIENTE'), ('sugestao', 'SUGESTÃO'), ('outros', 'OUTRO')], max_length=20),
        ),
    ]
