# Generated by Django 4.2.5 on 2023-10-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0006_merge_20231023_1849'),
        ('reclamacoes', '0010_alter_reclamacoes_options_alter_reclamacoes_nome_and_more'),
    ]

    operations = [
    ]
