# Generated by Django 4.2.7 on 2023-11-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0006_merge_20231023_1918'),
        ('reclamacoes', '0011_merge_20231028_1903'),
    ]

    operations = [
    ]
